name: first-workflow
on: workflow_dispatch
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: first-steps
        uses: actions/checkout@v3
      - name: second-steps
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: installing npm
        run: npm ci
      - name: run tests
        run: npm test
  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: printing github context object
        run: echo "object ${{toJSON(github)}}"
