name: first-workflow
on:
  pull_request:
    types: # used types
      - opened
      - closed
  workflow_dispatch:
  push:
    paths: # used filters
      - '.github/workflows/*'
jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: code-checkout
        uses: actions/checkout@v3
      - name: installing-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: installing packages
        run: npm install
      - name: run tests
        run: npm test

  second-job:
    needs: first-job
    runs-on: ubuntu-latest
    steps:
      - name: doing-codecheckout
        uses: actions/checkout@v3
      - name: installing-node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: installing-npm
        run: npm install
      - name: build-artifact
        run: npm run build

  third-job:
    needs: second-job
    runs-on: ubuntu-latest
    steps:
      - name: printing github context object
        run: echo "object ${{toJSON(github)}}"
  
  fourth-job:
    needs: third-job
    runs-on: ubuntu-latest
    steps:
      - name: printing-event of github object
        run: echo "{{to_JSON(github.event)}}"
